
STOISTAGE1 = {'during_pt': 0, 
              'out_of_pt': 1,
              'serve_bot': 2,
              'serve_top': 3,
              'winner_bot': 4,
              'winner_top': 5}

ITOSSTAGE1 = {0: 'during_pt',
              1: 'out_of_pt',
              2: 'serve_bot',
              3: 'serve_top',
              4: 'winner_bot',
              5: 'winner_top'}

STOISTAGE2 = {'back_hand_cross': 0,
            'back_hand_line': 1,
            'back_hand_mid': 2,
            'bot_serve': 3,
            'forehand_cross': 4,
            'forehand_inside_in': 5,
            'forehand_inside_out': 6,
            'forehand_line': 7,
            'forehand_mid': 8,
            'miss': 9,
            'ret_backhand_cross': 10,
            'ret_backhand_inside_in': 11,
            'ret_backhand_inside_out': 12,
            'ret_backhand_line': 13,
            'ret_backhand_mid': 14,
            'ret_forehand_cross': 15,
            'ret_forehand_inside_in': 16,
            'ret_forehand_inside_out': 17,
            'ret_forehand_line': 18,
            'ret_forehand_mid': 19,
            'serve_ad_mid': 20,
            'serve_ad_t': 21,
            'serve_ad_wide': 22,
            'serve_deuce_mid': 23,
            'serve_deuce_t': 24,
            'serve_deuce_wide': 25,
            'serve_miss': 26,
            'top_serve': 27,
            'volley': 28,
            'winner_bot': 29,
            'winner_top': 30,
            'z': 31}

ITOSSTAGE2 = {0: 'back_hand_cross',
            1: 'back_hand_line',
            2: 'back_hand_mid',
            3: 'bot_serve',
            4: 'forehand_cross',
            5: 'forehand_inside_in ',
            6: 'forehand_inside_out',
            7: 'forehand_line',
            8: 'forehand_mid',
            9: 'miss',
            10: 'ret_backhand_cross',
            11: 'ret_backhand_inside_in',
            12: 'ret_backhand_inside_out',
            13: 'ret_backhand_line',
            14: 'ret_backhand_mid',
            15: 'ret_forehand_cross',
            16: 'ret_forehand_inside_in',
            17: 'ret_forehand_inside_out',
            18: 'ret_forehand_line',
            19: 'ret_forehand_mid',
            20: 'serve_ad_mid',
            21: 'serve_ad_t',
            22: 'serve_ad_wide',
            23: 'serve_deuce_mid',
            24: 'serve_deuce_t',
            25: 'serve_deuce_wide',
            26: 'serve_miss',
            27: 'top_serve',
            28: 'volley',
            29: 'winner_bot',
            30: 'winner_top',
            31: 'z'}

POINTSEPARATOR = 31

CLASSCOUNT = [59, 30, 29, 46, 54, 24, 33, 30, 30, 50, 12,  6,  6,  3, 21,  5,  3, 3,  5, 18, 10, 17, 15, 16, 17, 11, 31, 43, 29, 37, 52, 89]

